### PR TITLE
[FIX] Duplicate import in init file.

### PR DESCRIPTION
**Pull request by adrienpeiffer**

### CODE REVIEW

**Comment by sbidoul** [comment]
doubt

**Comment by sbidoul** [comment]
Could you clarify why this change is necessary?

**Comment by ThomasBinsfeld** [comment]
@sbidoul 
**Steps to reproduce:** _(in a module with a least one model)_
* create a new model in the module with `mrbob bobtemplates.odoo:model`
* follow the usual steps

--> The model is created but `from . import models` has been added in the existing `__init__.py` of the module, resulting with a duplicate in this file.

The bug exists with wizard creation too.

**Comment by sbidoul** [comment]
This issue was apparently introduced in ea819a842c3894efccdc7043f118f5781c5d582b

**Pull request closed without merging**
