### PR TITLE
[IMP] Take into account OCA README generator

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@sbidoul

**Comment by sbidoul** [comment]
Good. To me the code in the hook goes too far for little added value. Especially since we have basically no test, that code is going to be very hard to maintain.

**Comment by rousseldenis** [comment]
@sbidoul About what? Summary or git contributor ?

**Comment by sbidoul** [comment]
Actually, when I told you about that, all I had in mind was to copy the readme folder of the OCA template to the mrbob template and that's all: no code, no hook, no variables.

**Comment by rousseldenis** [comment]
Ok, that was because there was logic about README file in hook, so I supposed I've to modify it accordingly (even if I went further...).

If you think it is too bulky, I remove it.

**Comment by sbidoul** [comment]
@rousseldenis Yes I'd remove it. Actually, what we could do is a `request.get()` of the fragments from the OCA github, so we always have the latest version.

**Comment by blaggacao** [comment]
Probably you also do the readme later down the road, not when you first bootstrap an addon... I still didn't figure out if mrbob manages reconciliation loops, but assuming that not, it should be a separate `bobtemplates.odoo:readme`

**Comment by blaggacao** [comment]
I've tried some things on this one, locally. I guess it's a bad idea to just popularize a readme directory with the default files: It flaws this magic templating productivity boost.

**Comment by rousseldenis** [comment]
@sbidoul @blaggacao So, what's your conclusions on this ?

**Comment by blaggacao** [comment]
I'm still analyzing the topic. If i were to implement a readme template, I'd implement it rather as an afterthought, meaning: `mrbob bobtemplates.odoo readme`. BUT, some use the readme as sort of the starting point of a module development, in other words a type of "lean specification". I'm not sure if that practice is really reflected in the OCA/Readme template... But it makes utterly sense from the perspective of a development workflow. I'll never be a friend with OCA multi-module-per-repo structure, so I'll probably leave out on OCA/Readme for now and rather implement a truly useful workflow (`spec`/`readme`). Still some thinking and meditation necessary, though.

**Comment by rousseldenis** [comment]
#55 does it in a better way.

**Pull request closed without merging**
