### PR TITLE
[FIX] icon.png

### PR DESCRIPTION
**Pull request by ThomasBinsfeld**
Icon of an addon should be `icon.png`, `icon.svg` is not required if it is the unchanged OCA logo. 

[OCA maintainer tools](https://github.com/OCA/maintainer-tools/tree/master/template/module/static/description)

### CODE REVIEW

**Comment by sbidoul** [comment]
@ThomasBinsfeld https://github.com/acsone/bobtemplates.odoo/blob/b75059209fd39f74306cf60e1e6506a237b21ab8/tests/test_templates.py#L67

**Comment by ThomasBinsfeld** [comment]
@sbidoul Yes, I'm on it

**Comment by sbidoul** [comment]
Can you add a line in https://github.com/acsone/bobtemplates.odoo/blob/master/CHANGES.rst too?

**Comment by ThomasBinsfeld** [comment]
@sbidoul Yes, under a new title **1.0.0b5 (unreleased)** so ?

**Comment by sbidoul** [comment]
@ThomasBinsfeld no, at the end of 1.0.0b4 since it is not yet released.

**Pull request merged**
