### PR TITLE
[ADD] Add fields to model templates

### PR DESCRIPTION
**Pull request by chermed**
Make some fields generator

`model.fields = name:translate sequence user_id:res.users:Responsible state:draft,confirm,done,cancel description:text count:compute:inverse date_creation:readonly:required:datetime`

gives :

```
@api.multi
@api.depends() #TODO
def _compute_count(self):
    for obj in self:
        obj.count = False #TODO

@api.one
def _inverse_count(self):
    if self.count:
        pass #TODO
count = fields.Integer(string='Count', store=False, compute='_compute_count', inverse='_inverse_count', )
user_id = fields.Many2one('res.users', string='Responsible', )
description = fields.Text(string='Description', )
sequence = fields.Integer(string='Sequence', )
state = fields.Selection([(u'draft', u'Draft'), (u'confirm', u'Confirm'), (u'done', u'Done'), (u'cancel', u'Cancel')], string='State', readonly=True, default='draft', )
date_creation = fields.Datetime(string='Date_creation', readonly=True, required=True, )
name = fields.Char(string='Name', translate=True, )
```

### CODE REVIEW

**Comment by sbidoul** [comment]
@chermed thanks a lot for contributing to this project. It's good to see!

I understand your proposal is to add a fields question to the model template. That's interesting. I'm wondering if it would be possible to add a standalone field template that would look for the proper class and add fields to it. So it would be possible to invoke it several times.

It's probably a bit harder to implement (maybe with some ast processing?), but it would be more fit with the current philosophy of the lib.

**Comment by blaggacao** [comment]
> maybe with some ast processing?

Did you think of presenting a selection of the models as a question? I'm trying to wrap my head around this as it seems especially interesting for computed fields

**Comment by blaggacao** [comment]
Just noting down a few question through the cycle before I forget them again:
- Which model (dot notation)? (ast-analyse addon, present through choice, eg. `pick`)
- Which type? (ast-analyse fields.py of `odoo` package, present through choice, eg. `pick`)
- cmodel / inverse?
- Field snake_case_name?
- Help text? (Think before you do...)
- Is computed (company/related/computed)?
-- depends specification (if computed)?
-- stored?
- Add to form?  (pre_ask: if form has been defined - through mr.bob)
- Add to list? (pre_ask: if list has been defined - through mr.bob)
- Add to search? (pre_ask: if search has been defined - through mr.bob)

**Comment by blaggacao** [comment]
https://github.com/wong2/pick

**Pull request closed without merging**
